export const useArticles = ()=>useState(()=>[])
export const useMoreArticles = ()=>useState(()=>[])
export const usePosters = () => useState(()=>[])
export const useReadArticles = ()=> useState(()=>[])
export const useShows = ()=> useState(()=>[])
export const useBrands = ()=> useState(()=>[])
export const useFoodSlug = ()=> useState(()=>[])